services:
  db:
    image: postgres:latest
    container_name: postgres-ms-user
    environment:
      POSTGRES_PASSWORD: post123
      POSTGRES_USER: post123
      POSTGRES_DB: ms-user
    ports:
      - 5432:5432