
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: ${RABBIT_URL}

broker:
  queue:
    email:
      name: default.email